# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AK_7RgF1DK9IalAG2x_iRIUICRtljpFx
"""

import random
player_score = 0
pc_score = 0
while True:
  computer = random.randint(1 , 3)
  player = int(input("Введите свой вариант(1 - камень 2 ножницы 3 бумага): "))
  if computer == player:
    print("Ничья")
    print(computer)
  elif (player == 1 and computer == 2) or (player == 2 and computer == 3) or (player == 3 and computer == 1):
    player_score += 1
    print("Победа")
    print(computer)
  elif (player == 1 and computer == 3) or (player == 2 and computer == 1) or (player == 1 and computer == 3):
    pc_score += 1
    print("Поражение")
    print(computer)
  if player_score == 3 or pc_score == 3:
    print("Ты победил") if player_score == 3 else print("Ты проиграл машинам")
    cont = input("Do you wont to continue (yes/no)? ")
    if cont == "no":
      print("bye")
      break
    else:
      pc_score = 0
      player_score = 0